### ISSUE TITLE
CIE Review materials

### ISSUE THREAD

**Issue by jimianelli** [seacode/gmacs#104]
## Materials to distribute to CIE panel
**Due June 15 2015** 

- [x] SSC and CPT Minutes.
- [x] Links to wiki (needs updating?).
- [x] Presentation to CPT May 2015.
- [ ] Updated documentation of model.
- [x] BBRKC assessment (from Jie).
- [ ] Side-by-side comparisons of BBRKC model.
- [x] Poster from Wakefield symposium showing results from SRA-like model through to "data rich"
- [ ] Others ...

**Comment by quantifish** [comment]
I'm working on updating the wiki and README docs at the moment. Also working on the knitr BBRKC comparison.

**Comment by quantifish** [comment]
Hey Jim, any "Updated documentation of model" in particular that you want me working on?
