### ISSUE TITLE
Growth transition code evolution for FUNCTION calc_growth_transition

### ISSUE THREAD

**Issue by jimianelli** [seacode/gmacs#112]
From comment in code (moved to issues)
* 
	 * Modified Dec 11, 2014.  Diagonal of the matrix now represents probability
	 * of not molting, and upper triangle is the probability of growing to the next
	 * size interval given you molted. 
	 * 
	 * Dec 20.  Undid the above modification after correspondence with Jack Turnock.
	 * He rightly pointed out that it is possible to molt and remain in the same bin
	 * interval (if the intervals are sufficiently large). 
	 * 
	 * Jan 11, 2015. Checked cumd_gamma function in ADMB with R.  This is the same
	 * function as pgamma with the rate parameter set at its default value 1.0.  The 
	 * mean value of the function is the second argument of cumd_gamma, and the vector 
	 * of quantiles is the first argument.  Both arguments are scaled by gscale.
	 * 
	 * Jan 20, 2015.  Jim reported that cumd_gamma was not converging. Required large 
	 * number of iterations to solve the cumd_gamma function in gser in the ADMB libs.
	 * Soln, either increase the MAXIT in gser, or rescale the problem to the maximum
	 * of the size breaks.  The latter seems to work.
	 */

**Comment by quantifish** [comment]
"after correspondence with Jack Turnock.
He rightly pointed out that it is possible to molt and remain in the same bin
interval (if the intervals are sufficiently large)." - I was wondering if it is possible to shrink as well?
