### ISSUE TITLE
Missing Figures in Gmacs Beamer Presentation

### ISSUE THREAD

**Issue by smartell** [seacode/gmacs#116]
There are missing png files for the Beamer presentation in the repo.  So when I fixed a couple of typos, and pushed it back up, the Beamer.pdf is now missing the figures. Sorry about that.

Steve

**Comment by quantifish** [comment]
Oh, I've been working on that all day. I'll try to catch all the changes you made and work them into what I've got.

**Comment by smartell** [comment]
was just a couple of spelling mistakes.

Steve

**Comment by quantifish** [comment]
Sweet found em and included them, figure work, I'll push shortly as a lot more has been added
