### ISSUE TITLE
Likelihood can be optimized

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#118]
The current likelihoods use ADMB's dnorm function. For example

	for(int k = 1; k <= nSurveys; k++ )
	{
		dvector cpue_sd = sqrt(log(1.0 + square(cpue_cv(k))));
		nloglike(2,k) += cpue_lambda(k) * dnorm(res_cpue(k),cpue_sd(k));
	}

where `dnorm` is

00046 dvariable dnorm( const prevariable& x, const double& mu, const double& std )
00047 {
00048 
00049   if( std<=0 ) 
00050   {
00051     cerr<<"Standard deviation is less than or equal to zero in "
00052     "dnorm(const dvariable& x, const double& mu, const double& std)\n";
00053     return 0;
00054   }
00055 
00056   return 0.5*log(2.*M_PI)+log(std)+0.5*square(x-mu)/(std*std);
00057 }

This can be optimised by writing a more task specific likelihood.

**Comment by quantifish** [comment]
Also, likelihood for growth increments seems to be log-normal, I would recommend against this and propose to use normal or robust normal (I can get rock lobster code for this)

**Comment by smartell** [comment]
Not sure I follow what you mean by task specific liklelihood?

Re log-normal likelihood.  Both options would be great

**Comment by quantifish** [comment]
I just mean removing the 0.5log(2.M_PI) and potentially the log(std) bit as well if std in a constant. Can help speed up MCMC's.
