### ISSUE TITLE
Catchability priors code unfinished

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#133]
// ---Continue with catchability priors-----------------------
	int iprior = ntheta + nGrwth + 1; 
	for (int i=1; i<=nSurveys; i++)
	{
		int itype = int(prior_qtype(i));
		switch(itype)
		{
			// Analytical soln, no prior (uniform, uniformative)
			case 0:
			break;
			// Prior on analytical soln, log-normal
			case 1:
				priorDensity(iprior) = dnorm(log(survey_q(i)),log(prior_qbar(i)),prior_qsd(i));
			break;
		}
		iprior++;
	}

**Comment by smartell** [comment]
what is unfinished?  Can add more options.

**Comment by quantifish** [comment]
I presume case 0 should be a uniform rather than just a constant prior? Or could add both as options...

**Comment by quantifish** [comment]
I've made this change from constant to uniform line 2128 of gmacs.tpl
