### ISSUE TITLE
Need to estimate discards for years that we dont have data...

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#135]
but we do have retained catch data

**Comment by smartell** [comment]
I think all that is need here is an array to store the predicted discarded catch.  It's already calculated visa vie the retained catch equations.

**Comment by jimianelli** [comment]
so this means the plot showing predicted discards against observed should probably show the full time series (i.e., also for years that discard data are unavailable)

**Comment by quantifish** [comment]
done, plots done too.
