### ISSUE TITLE
Size composition naming convention

### ISSUE THREAD

**Issue by jimianelli** [seacode/gmacs#140]
As part of #103, re getting the sex and shell type condition correct for size compositions, consider defining shape of observations using current names for arrays used (e.g., d3_obs_comps ) and use some other convention for when they are read in (e.g., d3_obs_comps_in ).

This should help when in simulation mode and in defining the analogous predictions (no need to replicate the data as read in) and save on awkward naming. That is, avoid using "Agg" in name as seems to be done presently in the size-comp branch.

**Comment by quantifish** [comment]
This has been changed in the size-comp-changes branch.  Code that aggregates size-comp observations together has been written.  Now I just need to figure out how to match up the observed with the predicted.
