### ISSUE TITLE
DoubleNormal selectivity

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#145]
Here's an ADMB question for ya'll. I've written the double normal selectivity function as

```
template<class T, class T2>
inline
const T pdubnorm(const T &x, const T2 &sL, const T2 &s50, const T2 &sR)
{
    T selex = pow(2,-pow((x-sL)/sL,2)); // if x <= s50
    T selex = pow(2,-pow((x-sR)/sL,2); // if x > s50
    return selex;
}
```

Obviously this won't work, but I am wondering if there is some elegant ADMB function for specifying the if statement that I've commented out at the right???

Also, need to get coefficients working.

**Comment by wStockhausen** [comment]
In SS, it's done with a steep logistic curve, something like:

S(x) = S_1(x)*(1-L(x) )+ S_2(x)*L(x)

where S_1 and S_2 are the x<s50 and x>s50 functions (following your
example), and L(x) is a logistic that rises rapidly from 0 to 1 in the
neighborhood of s50 (say with a slope of 100).

Buck

***************************************************
* Dr. William T. Stockhausen                      *
***************************************************
* Resource Ecology and Fisheries Management       *
* Alaska Fisheries Science Center                 *
* National Marine Fisheries Service               *
* National Oceanic and Atmospheric Administration *
* 7600 Sand Point Way N.E.                        *
* Seattle, Washington 98115-6349                  *
***************************************************
* email: William.Stockhausen@noaa.gov             *
* voice: 206-526-4241 fax: 206-526-6723           *
* web  : http://www.afsc.noaa.gov                 *
***************************************************
All models are wrong, some are useful.--G.E.P. Box
Beware of geeks bearing equations.    --W. Buffett
***************************************************
Disclaimer: The opinions expressed above are personal
and do not necessarily reflect official NOAA policy.
