### ISSUE TITLE
make test from root directory fails

### ISSUE THREAD

**Issue by jimianelli** [seacode/gmacs#147]
for demo and bbrkc/M1, minor issue but could perhaps be a way to test if ctl files all have right dimensions etc...

**Comment by quantifish** [comment]
Yeah, everything but bbrkc/OneSex and TwoSex will fail at the moment as 
the changes made for size comps and selectivity resulted in a fair few 
changes to the .ctl files. I've yet to implement these changes across 
the other examples. Sorry


On 15-09-02 11:06 AM, Jim Ianelli wrote:
>
> for demo and bbrkc/M1, minor issue but could perhaps be a way to test 
> if ctl files all have right dimensions etc...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/seacode/gmacs/issues/147>.
>

-- 
--------------------------------------------------
D'Arcy Webber
Quantifish | Quantitative Marine Science Solutions
P: +6421 0233 0163
E: darcy@quantifish.co.nz
W: www.quantifish.co.nz
--------------------------------------------------

**Comment by jimianelli** [comment]
no worries, just a placeholder and this is something I should do to get up to speed on the changes you've made
