### ISSUE TITLE
selectivity from BBRKC Assessment (Zheng et al 2015)

### ISSUE THREAD

**Issue by jimianelli** [seacode/gmacs#151]
Here are the selectivities by period 
![image](https://cloud.githubusercontent.com/assets/2715618/9750996/17e8bcde-5654-11e5-9bb6-8a9643600330.png)

![image](https://cloud.githubusercontent.com/assets/2715618/9751021/4c0c6be6-5654-11e5-9fac-90bdb5237992.png)

**Comment by jimianelli** [comment]
Here are values from the 2014 assessment, perhaps we're comparing 2013 assessment values...

![image](https://cloud.githubusercontent.com/assets/2715618/9751116/a0492716-5655-11e5-9595-a3c9d62c33aa.png)
![image](https://cloud.githubusercontent.com/assets/2715618/9751119/b4d4f1a6-5655-11e5-8258-4961a27ac64e.png)

**Comment by quantifish** [comment]
pg 45 STAN manual: This Jacobian adjustment is turned off when optimization is being applied in order
to produce appropriate maximum likelihood estimates.

**Comment by jimianelli** [comment]
interesting comment...my recollection is that Jacobians matter when variance of derived parameters are being estimated...

**Comment by quantifish** [comment]
Ya, I'm not sure myself. I'll do some more digging and let you know.
