### ISSUE TITLE
Should gmr be in its own repository

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#163]
At the meeting in Jan Buck suggested that it is easier to have `gmr` in its own repo because he can do stuff with it from RStudio that way. Should we do this? I am not fussed either way.

**Comment by smartell** [comment]
If all the R-code for gmr is in one directory, can't he just pull that specific directory?  I'm not fussed either.  But just a thought.

**Comment by quantifish** [comment]
I don't use RStudio so I'm unsure, but I think it has something to do with installing directly from within an RStudio terminal from GitHub without doing any pulling?

**Comment by wStockhausen** [comment]
I suppose if you can pull/push a specific directory, that would probably
work. Didn't know you could do that.

Buck

***************************************************
* Dr. William T. Stockhausen                      *
***************************************************
* Resource Ecology and Fisheries Management       *
* Alaska Fisheries Science Center                 *
* National Marine Fisheries Service               *
* National Oceanic and Atmospheric Administration *
* 7600 Sand Point Way N.E.                        *
* Seattle, Washington 98115-6349                  *
***************************************************
* email: William.Stockhausen@noaa.gov             *
* voice: 206-526-4241 fax: 206-526-6723           *
* web  : http://www.afsc.noaa.gov                 *
***************************************************
All models are wrong, some are useful.--G.E.P. Box
Beware of geeks bearing equations.    --W. Buffett
***************************************************
Disclaimer: The opinions expressed above are personal
and do not necessarily reflect official NOAA policy.

**Comment by quantifish** [comment]
You can also use `devtools` from within R to install with:

    install.packages("devtools")
    devtools::install_github("seacode/gmacs", subdir = "/gmr", ref = "develop")

This can be a little slow but works.
