### ISSUE TITLE
Small bycatches

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#173]
In dat file, if we have a really small bycatch then we are simply adding 0.0001 to stop log issues (to the dat file). It may be better for gmacs to add TINY automatically to catches that are zero (or all catches)

**Comment by smartell** [comment]
long live TINY!
S
> On May 11, 2016, at 4:04 PM, Darcy Webber <notifications@github.com> wrote:
> 
> In dat file, if we have a really small bycatch then we are simply adding 0.0001 to stop log issues (to the dat file). It may be better for gmacs to add TINY automatically to catches that are zero (or all catches)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/seacode/gmacs/issues/173>

Steve Martell
martell.steve@gmail.com

**Comment by quantifish** [comment]
Done and tested.
