### ISSUE TITLE
solve for beta initial value in preliminary calcs section

### ISSUE THREAD

**Issue by jimianellil** [seacode/gmacs#44]
since linear, and sensitive in the active search part, evaluate solving for MLE in prelim calcs section (beta = sum(x*y)/sum(x^2) ) may improve sensitivity of growth by sex in early phases.

**Comment by smartell** [comment]
This is now implemented. There is a flag in the control file that user can specificy linear model, which is then initialized using the MLE estimates for slope and intercept.  Good suggestion @jimianellil
