### ISSUE TITLE
BBRKC case, use mature growth increment data for fitting purposes

### ISSUE THREAD

**Issue by jimianellil** [seacode/gmacs#46]
fitting a straight line through the kinked-data / relationship for females will bias the growth increment too high for mature female crab, better to have growth increment biased low for immature crabs...

Future option would be to allow flexibitility in growth increment relationship to pre-molt size

**Comment by smartell** [comment]
Added the option of using empirical growth increment data.  For the bbrck case, i just fit a smoother to the male and female data in R, and then used the output in the data file.
