### ISSUE TITLE
make issue w/ current clone

### ISSUE THREAD

**Issue by kellijohnson** [seacode/gmacs#54]
Should you be able to run ``make`` from a current cloned version of the repository? I can only get gmacs to compile if I download the zipped version referenced in the wiki. I am on a windows (if that matters). The error message I am getting is "gmacs.cpp:2200:14: error: 'nullptr' was not declared in this scope spr *ptrSPR=nullptr;"

**Comment by amoeba** [comment]
I ran into a compile-time error with the latest gmacs yesterday and resolved it by pulling the latest ADMB source and compiling that first. I had a different error so I'm not sure that'll help but it's worth a shot.

**Comment by smartell** [comment]
Hi Kelli: nullptr is not supported by older versions of gcc.   I changed the line of code to *ptrSPR=0; this seems to work.

**Comment by kellijohnson** [comment]
thanks it now compiles on the older version of gcc.
