### ISSUE TITLE
Check selectivities for BBRKC model

### ISSUE THREAD

**Issue by smartell** [seacode/gmacs#62]
There are a few issues with estimation of selectivity parameters (especially the coefficients) that need to be debugged.

**Comment by jimianellil** [comment]
hmm, can't make sense of much of the selectivity specifications. Jack put bounds on the logged-params that affect type 2 and 3...but mirroring seems to fail as well. Now that growth is specified and works (broadly) the selectivities need to have features:
  * set ub and lb in the ctl file
  * phase specific, and expands for single vs split sex
   * add flexibility in the + group (e.g., add parameter that specifies number of bins at largest size are equal to eachother

**Comment by smartell** [comment]
Have we fixed this yet?  I don't see any references to #62

**Comment by smartell** [comment]
This is now fixed in #75
