### ISSUE TITLE
change ra, rbeta parameters to ln-scale

### ISSUE THREAD

**Issue by wStockhausen** [seacode/gmacs#67]
Recommend you change input recruitment parameters ra, rbeta (theta(5), theta(6)) to ln-scale, since they are positive definite.

**Comment by smartell** [comment]
I agree, this is probably a good idea

**Comment by jimianelli** [comment]
See branch iss67, am thinking may be undesirable because theta specifications are presently bounded parameters...

**Comment by quantifish** [comment]
I just referenced this in issue #144. I'd like to get peoples input on this before progressing.
