### ISSUE TITLE
Travis CI for gmr

### ISSUE THREAD

**Issue by quantifish** [seacode/gmacs#86]
Add Travis Ci to gmr package

**Comment by quantifish** [comment]
I don't seem to have access to gmacs via travis. Can one of you fella's enable gmacs/gmr on travis?

**Comment by smartell** [comment]
did you ever get this working?

**Comment by quantifish** [comment]
No never did. Hopefully will figure it out at some point...

--------------------------------------------------

Darcy Webber, PhD

Quantifish | Quantitative Marine Science Solutions

P: +6421 0233 0163

E: darcy@quantifish.co.nz

--------------------------------------------------
